FROM maven:3.8.2-jdk-11

COPY /grpc /opt/grpc

WORKDIR /opt/grpc

RUN mvn clean compile package -DskipTests

FROM openjdk:11.0.4-jre-slim

WORKDIR /opt

COPY --from=0 /opt/grpc/target/grpc-1.0-SNAPSHOT-jar-with-dependencies.jar grpc-1.0-SNAPSHOT-jar-with-dependencies.jar

EXPOSE 8080

CMD ["/bin/sh", "-c", "java -jar grpc-1.0-SNAPSHOT-jar-with-dependencies.jar"]